apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-coe-client-deployment
  namespace: aicoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-coe-client
  template:
    metadata:
      labels:
        app: ai-coe-client
    spec:
      containers:
      - name: ai-coe-client
        image: testcrumt360.azurecr.io/ai-coe-client:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-coe-client-service
  namespace: aicoe
spec:
  selector:
    app: ai-coe-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer